#
#	SkriptInstaller - config.yml
#	By nfell2009
#	All rights reserved.
#

files:
  save:
    files: 1
    1:
      name: ReadMe.sk
      local: true
      url: false
  delete:
    files: 0
    1:
      name: ReadMe.sk
  addons:
    files: 0
    1:
      name: SkQuery.jar
      local: true
      url: false
      overwrite: false